# Airline Passenger Satisfaction Analysis

## Task 3: Feature Engineering

**Intern:** Nagaraj V Kumbar

**Organization:** RD INFRO TECHNOLOGY

---

### Objective

The objective of this notebook is to prepare the cleaned dataset for machine learning by converting categorical variables into numerical values and scaling numerical features.

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../outputs/cleaned_airline.csv")

In [3]:
df.head()

,id,gender,customer_type,age,type_of_travel,class,flight_distance,inflight_wifi_service,departure/arrival_time_convenient,ease_of_online_booking,...,inflight_entertainment,on-board_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [4]:
df.head()

,id,gender,customer_type,age,type_of_travel,class,flight_distance,inflight_wifi_service,departure/arrival_time_convenient,ease_of_online_booking,...,inflight_entertainment,on-board_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

## 1. Dataset Information

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 24 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id                                 103904 non-null  int64
 1   gender                             103904 non-null  str
 2   customer_type                      103904 non-null  str
 3   age                                103904 non-null  int64
 4   type_of_travel                     103904 non-null  str
 5   class                              103904 non-null  str
 6   flight_distance                    103904 non-null  int64
 7   inflight_wifi_service              103904 non-null  int64
 8   departure/arrival_time_convenient  103904 non-null  int64
 9   ease_of_online_booking             103904 non-null  int64
 10  gate_location                      103904 non-null  int64
 11  food_and_drink                     103904 non-null  int64
 12  online_boarding                    103904 non-null  int64
 13  seat_comfort                       103904 non-null  int64
 14  inflight_entertainment             103904 non-null  int64
 15  on-board_service                   103904 non-null  int64
 16  leg_room_service                   103904 non-null  int64
 17  baggage_handling                   103904 non-null  int64
 18  checkin_service                    103904 non-null  int64
 19  inflight_service                   103904 non-null  int64
 20  cleanliness                        103904 non-null  int64
 21  departure_delay_in_minutes         103904 non-null  int64
 22  arrival_delay_in_minutes           103904 non-null  float64
 23  satisfaction                       103904 non-null  str
dtypes: float64(1), int64(18), str(5)
memory usage: 19.0 MB

## 2. Feature Encoding

from sklearn.preprocessing import LabelEncoder

In [10]:
encoder = LabelEncoder()

In [7]:
categorical_columns = [
    'gender',
    'customer_type',
    'type_of_travel',
    'class',
    'satisfaction'
]

In [11]:
for column in categorical_columns:
    df[column] = encoder.fit_transform(df[column])

In [12]:
df.head()

,id,gender,customer_type,age,type_of_travel,class,flight_distance,inflight_wifi_service,departure/arrival_time_convenient,ease_of_online_booking,...,inflight_entertainment,on-board_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,satisfaction
0,70172,1,0,13,1,2,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,0
1,5047,1,1,25,0,0,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,0
2,110028,0,0,26,0,0,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,1
3,24026,0,0,25,0,0,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,0
4,119299,1,0,61,0,0,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,1

## 3. Feature Scaling

In [13]:
scaler = StandardScaler()

In [14]:
numerical_columns = [
    'age',
    'flight_distance',
    'departure_delay_in_minutes',
    'arrival_delay_in_minutes'
]

In [15]:
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

In [16]:
df.head()

,id,gender,customer_type,age,type_of_travel,class,flight_distance,inflight_wifi_service,departure/arrival_time_convenient,ease_of_online_booking,...,inflight_entertainment,on-board_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,satisfaction
0,70172,1,0,-1.745279,1,2,-0.731539,3,4,3,...,5,4,3,4,4,5,5,0.266393,0.074169,0
1,5047,1,1,-0.951360,0,0,-0.957184,3,2,3,...,1,1,5,3,1,4,1,-0.361375,-0.236313,0
2,110028,0,0,-0.885200,0,0,-0.047584,2,2,2,...,5,4,3,4,4,4,5,-0.387532,-0.391554,1
3,24026,0,0,-0.951360,0,0,-0.629246,2,5,5,...,2,2,5,3,1,4,2,-0.099805,-0.158692,0
4,119299,1,0,1.430397,0,0,-0.978244,3,3,3,...,3,3,4,4,3,3,3,-0.387532,-0.391554,1

### Explanation

Feature scaling standardizes numerical variables so that all features contribute equally during machine learning model training.

### Explanation

Feature scaling standardizes numerical variables so that all features contribute equally during machine learning model training.

## 4. Save Processed Dataset

In [17]:
df.to_csv("../outputs/processed_airline.csv", index=False)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

# Final Conclusion

Feature engineering transformed categorical variables into numerical values and standardized important numerical features.

The processed dataset is now ready for machine learning model development and predictive analysis.